DROP TABLE moyennes CASCADE;
DROP TABLE evaluation CASCADE;
DROP TABLE cours CASCADE;
DROP TABLE salle CASCADE;
DROP TABLE etudiant CASCADE;
DROP TABLE intervenant CASCADE;
DROP TABLE matiere CASCADE;
